// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"
#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#include <winrt/Windows.Data.Json.h>

int initialize_Windows_Data_Json(PyObject* module);

namespace py
{
    template<>
    struct winrt_type<winrt::Windows::Data::Json::JsonArray>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::JsonError>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::JsonObject>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::JsonValue>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonArray>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonArrayStatics>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonErrorStatics2>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonObject>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonObjectStatics>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonObjectWithDefaultValues>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonValue>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonValueStatics>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Data::Json::IJsonValueStatics2>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

}
