// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"
#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif
#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#include <winrt/Windows.Devices.Geolocation.h>

int initialize_Windows_Devices_Geolocation(PyObject* module);

namespace py
{
}
