// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"
#if __has_include("py.Windows.Graphics.DirectX.h")
#include "py.Windows.Graphics.DirectX.h"
#endif

#include <winrt/Windows.Graphics.DirectX.Direct3D11.h>

int initialize_Windows_Graphics_DirectX_Direct3D11(PyObject* module);

namespace py
{
    template<>
    struct converter<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription>
    {
        static winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DMultisampleDescription convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription>
    {
        static winrt::Windows::Graphics::DirectX::Direct3D11::Direct3DSurfaceDescription convert_to(PyObject* obj);
    };
    
}
