// WARNING: Please don't edit this file. It was generated by Python/WinRT

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

// ----- PropertySet class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::PropertySet>::python_type;

PyObject* PropertySet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::PropertySet instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static void PropertySet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* PropertySet_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::Windows::Foundation::IInspectable return_value = self->obj.Lookup(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::Windows::Foundation::IInspectable> return_value = self->obj.GetView();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::Windows::Foundation::IInspectable>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>> return_value = self->obj.First();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* PropertySet_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>* self, void* /*unused*/)
{
    try
    {
        auto return_value = self->obj.Size();
        return py::convert(return_value);
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyMethodDef PropertySet_methods[] = {
    { "Lookup", (PyCFunction)PropertySet_Lookup, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)PropertySet_HasKey, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)PropertySet_GetView, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)PropertySet_Insert, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)PropertySet_Remove, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)PropertySet_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)PropertySet_First, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef PropertySet_getset[] = {
    { const_cast<char*>("Size"), (getter)PropertySet_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot PropertySet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, PropertySet_dealloc },
    { Py_tp_new, PropertySet_new },
    { Py_tp_methods, PropertySet_methods },
    { Py_tp_getset, PropertySet_getset },
    { 0, nullptr },
};

static PyType_Spec PropertySet_Type_spec =
{
    "PropertySet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::PropertySet>),
    0,
    Py_TPFLAGS_DEFAULT,
    PropertySet_Type_slots
};

// ----- StringMap class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::StringMap>::python_type;

PyObject* StringMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::StringMap instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static void StringMap_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* StringMap_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::hstring return_value = self->obj.Lookup(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::hstring> return_value = self->obj.GetView();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::hstring>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::hstring>> return_value = self->obj.First();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* StringMap_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>* self, void* /*unused*/)
{
    try
    {
        auto return_value = self->obj.Size();
        return py::convert(return_value);
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyMethodDef StringMap_methods[] = {
    { "Lookup", (PyCFunction)StringMap_Lookup, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)StringMap_HasKey, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)StringMap_GetView, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)StringMap_Insert, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)StringMap_Remove, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)StringMap_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)StringMap_First, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef StringMap_getset[] = {
    { const_cast<char*>("Size"), (getter)StringMap_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot StringMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, StringMap_dealloc },
    { Py_tp_new, StringMap_new },
    { Py_tp_methods, StringMap_methods },
    { Py_tp_getset, StringMap_getset },
    { 0, nullptr },
};

static PyType_Spec StringMap_Type_spec =
{
    "StringMap",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::StringMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    StringMap_Type_slots
};

// ----- ValueSet class --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::ValueSet>::python_type;

PyObject* ValueSet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_TypeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::ValueSet instance{  };
            return py::wrap(instance, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static void ValueSet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* ValueSet_Lookup(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            winrt::Windows::Foundation::IInspectable return_value = self->obj.Lookup(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_HasKey(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            bool return_value = self->obj.HasKey(param0);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_GetView(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IMapView<winrt::hstring, winrt::Windows::Foundation::IInspectable> return_value = self->obj.GetView();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Insert(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 2)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);
            auto param1 = py::convert_to<winrt::Windows::Foundation::IInspectable>(args, 1);

            bool return_value = self->obj.Insert(param0, param1);

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Remove(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::hstring>(args, 0);

            self->obj.Remove(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_Clear(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            self->obj.Clear();
            Py_RETURN_NONE;
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_First(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, PyObject* args)
{ 
    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 0)
    {
        try
        {
            winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<winrt::hstring, winrt::Windows::Foundation::IInspectable>> return_value = self->obj.First();

            return py::convert(return_value);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static PyObject* ValueSet_get_Size(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>* self, void* /*unused*/)
{
    try
    {
        auto return_value = self->obj.Size();
        return py::convert(return_value);
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyMethodDef ValueSet_methods[] = {
    { "Lookup", (PyCFunction)ValueSet_Lookup, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)ValueSet_HasKey, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)ValueSet_GetView, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)ValueSet_Insert, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)ValueSet_Remove, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)ValueSet_Clear, METH_VARARGS, nullptr },
    { "First", (PyCFunction)ValueSet_First, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef ValueSet_getset[] = {
    { const_cast<char*>("Size"), (getter)ValueSet_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot ValueSet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, ValueSet_dealloc },
    { Py_tp_new, ValueSet_new },
    { Py_tp_methods, ValueSet_methods },
    { Py_tp_getset, ValueSet_getset },
    { 0, nullptr },
};

static PyType_Spec ValueSet_Type_spec =
{
    "ValueSet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::ValueSet>),
    0,
    Py_TPFLAGS_DEFAULT,
    ValueSet_Type_slots
};

// ----- IIterable parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIIterable>::python_type;

PyObject* IIterable_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IIterable is not activatable");
    return nullptr;
}

static void IIterable_dealloc(py::winrt_pinterface_wrapper<pyIIterable>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IIterable_First(py::winrt_pinterface_wrapper<pyIIterable>* self, PyObject* args)
{
    return self->obj->First(args);
}

static PyMethodDef IIterable_methods[] = {
    { "First", (PyCFunction)IIterable_First, METH_VARARGS, nullptr },
    { nullptr }
};

static PyType_Slot IIterable_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IIterable_dealloc },
    { Py_tp_new, IIterable_new },
    { Py_tp_methods, IIterable_methods },
    { 0, nullptr },
};

static PyType_Spec IIterable_Type_spec =
{
    "IIterable",
    sizeof(py::winrt_pinterface_wrapper<pyIIterable>),
    0,
    Py_TPFLAGS_DEFAULT,
    IIterable_Type_slots
};

// ----- IIterator parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIIterator>::python_type;

PyObject* IIterator_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IIterator is not activatable");
    return nullptr;
}

static void IIterator_dealloc(py::winrt_pinterface_wrapper<pyIIterator>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IIterator_MoveNext(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{
    return self->obj->MoveNext(args);
}

static PyObject* IIterator_GetMany(py::winrt_pinterface_wrapper<pyIIterator>* self, PyObject* args)
{
    return self->obj->GetMany(args);
}

static PyObject* IIterator_get_Current(py::winrt_pinterface_wrapper<pyIIterator>* self, void* /*unused*/)
{
    return self->obj->get_Current();
}

static PyObject* IIterator_get_HasCurrent(py::winrt_pinterface_wrapper<pyIIterator>* self, void* /*unused*/)
{
    return self->obj->get_HasCurrent();
}

static PyMethodDef IIterator_methods[] = {
    { "MoveNext", (PyCFunction)IIterator_MoveNext, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IIterator_GetMany, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef IIterator_getset[] = {
    { const_cast<char*>("Current"), (getter)IIterator_get_Current, nullptr, nullptr, nullptr },
    { const_cast<char*>("HasCurrent"), (getter)IIterator_get_HasCurrent, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IIterator_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IIterator_dealloc },
    { Py_tp_new, IIterator_new },
    { Py_tp_methods, IIterator_methods },
    { Py_tp_getset, IIterator_getset },
    { 0, nullptr },
};

static PyType_Spec IIterator_Type_spec =
{
    "IIterator",
    sizeof(py::winrt_pinterface_wrapper<pyIIterator>),
    0,
    Py_TPFLAGS_DEFAULT,
    IIterator_Type_slots
};

// ----- IKeyValuePair parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIKeyValuePair>::python_type;

PyObject* IKeyValuePair_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IKeyValuePair is not activatable");
    return nullptr;
}

static void IKeyValuePair_dealloc(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IKeyValuePair_get_Key(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self, void* /*unused*/)
{
    return self->obj->get_Key();
}

static PyObject* IKeyValuePair_get_Value(py::winrt_pinterface_wrapper<pyIKeyValuePair>* self, void* /*unused*/)
{
    return self->obj->get_Value();
}

static PyGetSetDef IKeyValuePair_getset[] = {
    { const_cast<char*>("Key"), (getter)IKeyValuePair_get_Key, nullptr, nullptr, nullptr },
    { const_cast<char*>("Value"), (getter)IKeyValuePair_get_Value, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IKeyValuePair_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IKeyValuePair_dealloc },
    { Py_tp_new, IKeyValuePair_new },
    { Py_tp_getset, IKeyValuePair_getset },
    { 0, nullptr },
};

static PyType_Spec IKeyValuePair_Type_spec =
{
    "IKeyValuePair",
    sizeof(py::winrt_pinterface_wrapper<pyIKeyValuePair>),
    0,
    Py_TPFLAGS_DEFAULT,
    IKeyValuePair_Type_slots
};

// ----- IMapChangedEventArgs parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIMapChangedEventArgs>::python_type;

PyObject* IMapChangedEventArgs_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IMapChangedEventArgs is not activatable");
    return nullptr;
}

static void IMapChangedEventArgs_dealloc(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IMapChangedEventArgs_get_CollectionChange(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self, void* /*unused*/)
{
    return self->obj->get_CollectionChange();
}

static PyObject* IMapChangedEventArgs_get_Key(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>* self, void* /*unused*/)
{
    return self->obj->get_Key();
}

static PyGetSetDef IMapChangedEventArgs_getset[] = {
    { const_cast<char*>("CollectionChange"), (getter)IMapChangedEventArgs_get_CollectionChange, nullptr, nullptr, nullptr },
    { const_cast<char*>("Key"), (getter)IMapChangedEventArgs_get_Key, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IMapChangedEventArgs_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMapChangedEventArgs_dealloc },
    { Py_tp_new, IMapChangedEventArgs_new },
    { Py_tp_getset, IMapChangedEventArgs_getset },
    { 0, nullptr },
};

static PyType_Spec IMapChangedEventArgs_Type_spec =
{
    "IMapChangedEventArgs",
    sizeof(py::winrt_pinterface_wrapper<pyIMapChangedEventArgs>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMapChangedEventArgs_Type_slots
};

// ----- IMapView parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIMapView>::python_type;

PyObject* IMapView_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IMapView is not activatable");
    return nullptr;
}

static void IMapView_dealloc(py::winrt_pinterface_wrapper<pyIMapView>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IMapView_Lookup(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{
    return self->obj->Lookup(args);
}

static PyObject* IMapView_HasKey(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{
    return self->obj->HasKey(args);
}

static PyObject* IMapView_Split(py::winrt_pinterface_wrapper<pyIMapView>* self, PyObject* args)
{
    return self->obj->Split(args);
}

static PyObject* IMapView_get_Size(py::winrt_pinterface_wrapper<pyIMapView>* self, void* /*unused*/)
{
    return self->obj->get_Size();
}

static PyMethodDef IMapView_methods[] = {
    { "Lookup", (PyCFunction)IMapView_Lookup, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IMapView_HasKey, METH_VARARGS, nullptr },
    { "Split", (PyCFunction)IMapView_Split, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef IMapView_getset[] = {
    { const_cast<char*>("Size"), (getter)IMapView_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IMapView_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMapView_dealloc },
    { Py_tp_new, IMapView_new },
    { Py_tp_methods, IMapView_methods },
    { Py_tp_getset, IMapView_getset },
    { 0, nullptr },
};

static PyType_Spec IMapView_Type_spec =
{
    "IMapView",
    sizeof(py::winrt_pinterface_wrapper<pyIMapView>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMapView_Type_slots
};

// ----- IMap parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIMap>::python_type;

PyObject* IMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IMap is not activatable");
    return nullptr;
}

static void IMap_dealloc(py::winrt_pinterface_wrapper<pyIMap>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IMap_Lookup(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->Lookup(args);
}

static PyObject* IMap_HasKey(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->HasKey(args);
}

static PyObject* IMap_GetView(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->GetView(args);
}

static PyObject* IMap_Insert(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->Insert(args);
}

static PyObject* IMap_Remove(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->Remove(args);
}

static PyObject* IMap_Clear(py::winrt_pinterface_wrapper<pyIMap>* self, PyObject* args)
{
    return self->obj->Clear(args);
}

static PyObject* IMap_get_Size(py::winrt_pinterface_wrapper<pyIMap>* self, void* /*unused*/)
{
    return self->obj->get_Size();
}

static PyMethodDef IMap_methods[] = {
    { "Lookup", (PyCFunction)IMap_Lookup, METH_VARARGS, nullptr },
    { "HasKey", (PyCFunction)IMap_HasKey, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IMap_GetView, METH_VARARGS, nullptr },
    { "Insert", (PyCFunction)IMap_Insert, METH_VARARGS, nullptr },
    { "Remove", (PyCFunction)IMap_Remove, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)IMap_Clear, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef IMap_getset[] = {
    { const_cast<char*>("Size"), (getter)IMap_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IMap_dealloc },
    { Py_tp_new, IMap_new },
    { Py_tp_methods, IMap_methods },
    { Py_tp_getset, IMap_getset },
    { 0, nullptr },
};

static PyType_Spec IMap_Type_spec =
{
    "IMap",
    sizeof(py::winrt_pinterface_wrapper<pyIMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    IMap_Type_slots
};

// ----- IObservableMap parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIObservableMap>::python_type;

PyObject* IObservableMap_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IObservableMap is not activatable");
    return nullptr;
}

static void IObservableMap_dealloc(py::winrt_pinterface_wrapper<pyIObservableMap>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyGetSetDef IObservableMap_getset[] = {
    { nullptr }
};

static PyType_Slot IObservableMap_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IObservableMap_dealloc },
    { Py_tp_new, IObservableMap_new },
    { Py_tp_getset, IObservableMap_getset },
    { 0, nullptr },
};

static PyType_Spec IObservableMap_Type_spec =
{
    "IObservableMap",
    sizeof(py::winrt_pinterface_wrapper<pyIObservableMap>),
    0,
    Py_TPFLAGS_DEFAULT,
    IObservableMap_Type_slots
};

// ----- IObservableVector parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIObservableVector>::python_type;

PyObject* IObservableVector_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IObservableVector is not activatable");
    return nullptr;
}

static void IObservableVector_dealloc(py::winrt_pinterface_wrapper<pyIObservableVector>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyGetSetDef IObservableVector_getset[] = {
    { nullptr }
};

static PyType_Slot IObservableVector_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IObservableVector_dealloc },
    { Py_tp_new, IObservableVector_new },
    { Py_tp_getset, IObservableVector_getset },
    { 0, nullptr },
};

static PyType_Spec IObservableVector_Type_spec =
{
    "IObservableVector",
    sizeof(py::winrt_pinterface_wrapper<pyIObservableVector>),
    0,
    Py_TPFLAGS_DEFAULT,
    IObservableVector_Type_slots
};

// ----- IPropertySet interface --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::IPropertySet>::python_type;

PyObject* IPropertySet_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_RuntimeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::Windows::Foundation::Collections::IPropertySet>(args, 0);
            return py::wrap(param0, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static void IPropertySet_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyType_Slot IPropertySet_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IPropertySet_dealloc },
    { Py_tp_new, IPropertySet_new },
    { 0, nullptr },
};

static PyType_Spec IPropertySet_Type_spec =
{
    "IPropertySet",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IPropertySet>),
    0,
    Py_TPFLAGS_DEFAULT,
    IPropertySet_Type_slots
};

// ----- IVectorChangedEventArgs interface --------------------
PyTypeObject* py::winrt_type<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::python_type;

PyObject* IVectorChangedEventArgs_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    if (kwds != nullptr)
    {
        PyErr_SetString(PyExc_RuntimeError, "keyword arguments not supported");
        return nullptr;
    }

    Py_ssize_t arg_count = PyTuple_Size(args);

    if (arg_count == 1)
    {
        try
        {
            auto param0 = py::convert_to<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>(args, 0);
            return py::wrap(param0, type);
        }
        catch (...)
        {
            return py::to_PyErr();
        }
    }
    else if (arg_count == -1)
    {
        return nullptr; 
    }

    PyErr_SetString(PyExc_RuntimeError, "Invalid parameter count");
    return nullptr;
}

static void IVectorChangedEventArgs_dealloc(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self)
{
    auto hash_value = std::hash<winrt::Windows::Foundation::IInspectable>{}(self->obj);
    py::wrapped_instance(hash_value, nullptr);
    self->obj = nullptr;
}

static PyObject* IVectorChangedEventArgs_get_CollectionChange(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self, void* /*unused*/)
{
    try
    {
        auto return_value = self->obj.CollectionChange();
        return py::convert(return_value);
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyObject* IVectorChangedEventArgs_get_Index(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>* self, void* /*unused*/)
{
    try
    {
        auto return_value = self->obj.Index();
        return py::convert(return_value);
    }
    catch (...)
    {
        return py::to_PyErr();
    }
}

static PyGetSetDef IVectorChangedEventArgs_getset[] = {
    { const_cast<char*>("CollectionChange"), (getter)IVectorChangedEventArgs_get_CollectionChange, nullptr, nullptr, nullptr },
    { const_cast<char*>("Index"), (getter)IVectorChangedEventArgs_get_Index, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IVectorChangedEventArgs_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVectorChangedEventArgs_dealloc },
    { Py_tp_new, IVectorChangedEventArgs_new },
    { Py_tp_getset, IVectorChangedEventArgs_getset },
    { 0, nullptr },
};

static PyType_Spec IVectorChangedEventArgs_Type_spec =
{
    "IVectorChangedEventArgs",
    sizeof(py::winrt_wrapper<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVectorChangedEventArgs_Type_slots
};

// ----- IVectorView parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIVectorView>::python_type;

PyObject* IVectorView_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IVectorView is not activatable");
    return nullptr;
}

static void IVectorView_dealloc(py::winrt_pinterface_wrapper<pyIVectorView>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IVectorView_GetAt(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{
    return self->obj->GetAt(args);
}

static PyObject* IVectorView_IndexOf(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{
    return self->obj->IndexOf(args);
}

static PyObject* IVectorView_GetMany(py::winrt_pinterface_wrapper<pyIVectorView>* self, PyObject* args)
{
    return self->obj->GetMany(args);
}

static PyObject* IVectorView_get_Size(py::winrt_pinterface_wrapper<pyIVectorView>* self, void* /*unused*/)
{
    return self->obj->get_Size();
}

static PyMethodDef IVectorView_methods[] = {
    { "GetAt", (PyCFunction)IVectorView_GetAt, METH_VARARGS, nullptr },
    { "IndexOf", (PyCFunction)IVectorView_IndexOf, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IVectorView_GetMany, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef IVectorView_getset[] = {
    { const_cast<char*>("Size"), (getter)IVectorView_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IVectorView_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVectorView_dealloc },
    { Py_tp_new, IVectorView_new },
    { Py_tp_methods, IVectorView_methods },
    { Py_tp_getset, IVectorView_getset },
    { 0, nullptr },
};

static PyType_Spec IVectorView_Type_spec =
{
    "IVectorView",
    sizeof(py::winrt_pinterface_wrapper<pyIVectorView>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVectorView_Type_slots
};

// ----- IVector parameterized interface --------------------
PyTypeObject* py::winrt_type<pyIVector>::python_type;

PyObject* IVector_new(PyTypeObject* type, PyObject* args, PyObject* kwds)
{
    // TODO implement QI in this pinterface constructor
    PyErr_SetString(PyExc_RuntimeError, "IVector is not activatable");
    return nullptr;
}

static void IVector_dealloc(py::winrt_pinterface_wrapper<pyIVector>* self)
{
    py::wrapped_instance(self->obj->hash(), nullptr);
    self->obj.release();
}

static PyObject* IVector_GetAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->GetAt(args);
}

static PyObject* IVector_GetView(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->GetView(args);
}

static PyObject* IVector_IndexOf(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->IndexOf(args);
}

static PyObject* IVector_SetAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->SetAt(args);
}

static PyObject* IVector_InsertAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->InsertAt(args);
}

static PyObject* IVector_RemoveAt(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->RemoveAt(args);
}

static PyObject* IVector_Append(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->Append(args);
}

static PyObject* IVector_RemoveAtEnd(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->RemoveAtEnd(args);
}

static PyObject* IVector_Clear(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->Clear(args);
}

static PyObject* IVector_GetMany(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->GetMany(args);
}

static PyObject* IVector_ReplaceAll(py::winrt_pinterface_wrapper<pyIVector>* self, PyObject* args)
{
    return self->obj->ReplaceAll(args);
}

static PyObject* IVector_get_Size(py::winrt_pinterface_wrapper<pyIVector>* self, void* /*unused*/)
{
    return self->obj->get_Size();
}

static PyMethodDef IVector_methods[] = {
    { "GetAt", (PyCFunction)IVector_GetAt, METH_VARARGS, nullptr },
    { "GetView", (PyCFunction)IVector_GetView, METH_VARARGS, nullptr },
    { "IndexOf", (PyCFunction)IVector_IndexOf, METH_VARARGS, nullptr },
    { "SetAt", (PyCFunction)IVector_SetAt, METH_VARARGS, nullptr },
    { "InsertAt", (PyCFunction)IVector_InsertAt, METH_VARARGS, nullptr },
    { "RemoveAt", (PyCFunction)IVector_RemoveAt, METH_VARARGS, nullptr },
    { "Append", (PyCFunction)IVector_Append, METH_VARARGS, nullptr },
    { "RemoveAtEnd", (PyCFunction)IVector_RemoveAtEnd, METH_VARARGS, nullptr },
    { "Clear", (PyCFunction)IVector_Clear, METH_VARARGS, nullptr },
    { "GetMany", (PyCFunction)IVector_GetMany, METH_VARARGS, nullptr },
    { "ReplaceAll", (PyCFunction)IVector_ReplaceAll, METH_VARARGS, nullptr },
    { nullptr }
};

static PyGetSetDef IVector_getset[] = {
    { const_cast<char*>("Size"), (getter)IVector_get_Size, nullptr, nullptr, nullptr },
    { nullptr }
};

static PyType_Slot IVector_Type_slots[] = 
{
    { Py_tp_base, nullptr }, // filled out in module init
    { Py_tp_dealloc, IVector_dealloc },
    { Py_tp_new, IVector_new },
    { Py_tp_methods, IVector_methods },
    { Py_tp_getset, IVector_getset },
    { 0, nullptr },
};

static PyType_Spec IVector_Type_spec =
{
    "IVector",
    sizeof(py::winrt_pinterface_wrapper<pyIVector>),
    0,
    Py_TPFLAGS_DEFAULT,
    IVector_Type_slots
};

// ----- Windows.Foundation.Collections Initialization --------------------

int initialize_Windows_Foundation_Collections(PyObject* module)
{
    PyObject* type_object{ nullptr };


    PropertySet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&PropertySet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "PropertySet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::PropertySet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    StringMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&StringMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "StringMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::StringMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    ValueSet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&ValueSet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "ValueSet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::ValueSet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IIterable_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IIterable_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IIterable", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIIterable>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IIterator_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IIterator_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IIterator", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIIterator>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IKeyValuePair_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IKeyValuePair_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IKeyValuePair", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIKeyValuePair>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMapChangedEventArgs_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMapChangedEventArgs_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMapChangedEventArgs", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMapChangedEventArgs>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMapView_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMapView_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMapView", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMapView>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IObservableMap_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IObservableMap_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IObservableMap", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIObservableMap>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IObservableVector_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IObservableVector_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IObservableVector", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIObservableVector>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IPropertySet_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IPropertySet_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IPropertySet", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::IPropertySet>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVectorChangedEventArgs_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVectorChangedEventArgs_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVectorChangedEventArgs", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVectorView_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVectorView_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVectorView", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIVectorView>::python_type = reinterpret_cast<PyTypeObject*>(type_object);

    IVector_Type_slots[0].pfunc = py::winrt_type<py::winrt_base>::python_type;
    type_object = PyType_FromSpec(&IVector_Type_spec);
    if (type_object == nullptr)
    {
        return -1;
    }
    if (PyModule_AddObject(module, "IVector", type_object) != 0)
    {
        return -1;
    }
    py::winrt_type<pyIVector>::python_type = reinterpret_cast<PyTypeObject*>(type_object);
    
    return 0;
}
