// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"

#include <winrt/Windows.Foundation.Numerics.h>

int initialize_Windows_Foundation_Numerics(PyObject* module);

namespace py
{
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::float3x2>
    {
        static winrt::Windows::Foundation::Numerics::float3x2 convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::float4x4>
    {
        static winrt::Windows::Foundation::Numerics::float4x4 convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::plane>
    {
        static winrt::Windows::Foundation::Numerics::plane convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::quaternion>
    {
        static winrt::Windows::Foundation::Numerics::quaternion convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::Rational>
    {
        static winrt::Windows::Foundation::Numerics::Rational convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::float2>
    {
        static winrt::Windows::Foundation::Numerics::float2 convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::float3>
    {
        static winrt::Windows::Foundation::Numerics::float3 convert_to(PyObject* obj);
    };
    
    template<>
    struct converter<winrt::Windows::Foundation::Numerics::float4>
    {
        static winrt::Windows::Foundation::Numerics::float4 convert_to(PyObject* obj);
    };
    
}
