// WARNING: Please don't edit this file. It was generated by Python/WinRT

#include "py.Windows.Graphics.DirectX.h"

// ----- Windows.Graphics.DirectX Initialization --------------------

int initialize_Windows_Graphics_DirectX(PyObject* module)
{
    PyObject* type_object{ nullptr };

    
    return 0;
}
