// WARNING: Please don't edit this file. It was generated by Python/WinRT

#pragma once

#include "pybase.h"
#if __has_include("py.Windows.Devices.Geolocation.h")
#include "py.Windows.Devices.Geolocation.h"
#endif
#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif
#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#include <winrt/Windows.Devices.Geolocation.Geofencing.h>

int initialize_Windows_Devices_Geolocation_Geofencing(PyObject* module);

namespace py
{
    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::Geofence>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::GeofenceMonitor>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::GeofenceStateChangeReport>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::IGeofence>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::IGeofenceFactory>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::IGeofenceMonitor>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::IGeofenceMonitorStatics>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Geolocation::Geofencing::IGeofenceStateChangeReport>
    {
        static PyTypeObject* python_type;

        static PyTypeObject* get_python_type()
        {
            return python_type;
        }
    };

}
